/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Igu;

import Logica.Controladora;
import Logica.Mascota;

/**
 *
 * @author profl
 */
public class Peluqueria extends javax.swing.JFrame {

    Controladora ctrl = new Controladora();

    /**
     * Creates new form frmPeluqueria
     */
    public Peluqueria() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jpImagen = new javax.swing.JPanel();
        lblImagenPelu = new javax.swing.JLabel();
        jpDatos = new javax.swing.JPanel();
        lblCliente = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblRaza = new javax.swing.JLabel();
        txtRaza = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        lblColor1 = new javax.swing.JLabel();
        cmbAlergico = new javax.swing.JComboBox<>();
        lblColor2 = new javax.swing.JLabel();
        cmbAtencionEspecial = new javax.swing.JComboBox<>();
        lblDueno = new javax.swing.JLabel();
        txtDueno = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        lblCelular1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jpBotones = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TPO 2 - PoloTic Misiones");
        setBackground(new java.awt.Color(51, 58, 48));
        setName("frmPeluqueria"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Cooper Black", 0, 45)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Peluqueria Canina");
        lblTitulo.setAlignmentY(0.0F);
        jpTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 100));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon("D:\\OneDrive\\Documentos\\NetBeansProjects\\TestJPA\\src\\Igu\\img\\silicon.png")); // NOI18N
        jpTitulo.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 230, 100));

        getContentPane().add(jpTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jpImagen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagenPelu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagenPelu.setIcon(new javax.swing.ImageIcon("D:\\OneDrive\\Documentos\\NetBeansProjects\\TestJPA\\src\\Igu\\img\\Pelucanina_original.png")); // NOI18N
        lblImagenPelu.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lblImagenPelu.setMaximumSize(new java.awt.Dimension(215, 270));
        lblImagenPelu.setMinimumSize(new java.awt.Dimension(215, 270));
        lblImagenPelu.setPreferredSize(new java.awt.Dimension(2, 300));
        lblImagenPelu.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jpImagen.add(lblImagenPelu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 350));

        getContentPane().add(jpImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 310, 400));

        jpDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alta de la Mascota", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N
        jpDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCliente.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblCliente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCliente.setText("Cliente Nº ");
        lblCliente.setPreferredSize(new java.awt.Dimension(50, 50));
        jpDatos.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 100, 30));

        txtCliente.setEditable(false);
        txtCliente.setFont(new java.awt.Font("Dubai", 1, 30)); // NOI18N
        txtCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpDatos.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 15, 160, 30));

        lblNombre.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setText("Nombre:");
        jpDatos.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, 30));

        txtNombre.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jpDatos.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 310, 30));

        lblRaza.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblRaza.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRaza.setText("Raza:");
        jpDatos.add(lblRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 100, 30));

        txtRaza.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jpDatos.add(txtRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 85, 310, 30));

        lblColor.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblColor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColor.setText("Color:");
        jpDatos.add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 30));

        txtColor.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jpDatos.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 310, 30));

        lblColor1.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblColor1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColor1.setText("Alergico:");
        jpDatos.add(lblColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 60, 30));

        cmbAlergico.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cmbAlergico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "SI", "No" }));
        jpDatos.add(cmbAlergico, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 100, 30));

        lblColor2.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblColor2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColor2.setText("Atención Especial:");
        jpDatos.add(lblColor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 130, 30));

        cmbAtencionEspecial.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cmbAtencionEspecial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Si", "No" }));
        jpDatos.add(cmbAtencionEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 100, 30));

        lblDueno.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblDueno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDueno.setText("Nombre Dueño:");
        jpDatos.add(lblDueno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, 30));

        txtDueno.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jpDatos.add(txtDueno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 310, 30));

        lblCelular.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblCelular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCelular.setText("Cel. Dueño:");
        jpDatos.add(lblCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 100, 30));

        txtCelular.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jpDatos.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 310, 30));

        lblCelular1.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblCelular1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCelular1.setText("Obsservaciones:");
        jpDatos.add(lblCelular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 100, 30));

        jScrollPane1.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N

        txtObservaciones.setColumns(20);
        txtObservaciones.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        jpDatos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 310, 110));

        getContentPane().add(jpDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 140, 450, 400));

        jpBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLimpiar.setFont(new java.awt.Font("Dubai", 0, 24)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon("D:\\OneDrive\\Documentos\\NetBeansProjects\\TestJPA\\src\\Igu\\img\\clean.png")); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jpBotones.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 160, 40));

        btnGuardar.setFont(new java.awt.Font("Dubai", 0, 24)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon("D:\\OneDrive\\Documentos\\NetBeansProjects\\TestJPA\\src\\Igu\\img\\save1.png")); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jpBotones.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 160, 40));

        lblMensaje.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpBotones.add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 370, 40));

        getContentPane().add(jpBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 800, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarDatos();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarDatos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * guardarDatos() --> permite guardar los datos en la controladora para los
     * textos es directo. para los boolean se verifica en el momento para el nro
     * de Cliente hay una verificación y luego el guardado de la información
     */
    private void guardarDatos() {
        Mascota can = new Mascota();
        can.setNombrePerro(txtNombre.getText().toUpperCase());
        can.setRaza(txtRaza.getText().toUpperCase());
        can.setColor(txtColor.getText().toUpperCase());

        can.setEsAlergico(false);
        if (cmbAlergico.getSelectedItem().equals("Si")) {
            can.setEsAlergico(true);
        }

        can.setTieneAtencionEpecial(false);
        if (cmbAtencionEspecial.getSelectedItem().equals("Si")) {
            can.setTieneAtencionEpecial(true);
        }

        can.setNombreDueño(txtDueno.getText().toUpperCase());
        can.setCelularDueño(txtCelular.getText().toUpperCase());
        can.setObservaciones(txtObservaciones.getText());

        can.setNumCliente(ctrl.proximoCliente());

        if (ctrl.guardarCan(can)) {
            txtCliente.setText(recuperaCliente());
            lblMensaje.setText("Mascota Guardada con EXITO !!!");
        } else {
            lblMensaje.setText("Algo paso con el guardado de las mascotas....  ");

        }

    }

    /**
     * limpiarDatos() --> Limpiar los datos del formulario y emite un mensaje
     * con la cantidad de mascotas guardadas
     */
    private void limpiarDatos() {
        txtCliente.setText("");
        txtNombre.setText("");
        txtRaza.setText("");
        txtColor.setText("");
        cmbAlergico.setSelectedIndex(0);
        cmbAtencionEspecial.setSelectedIndex(0);
        txtDueno.setText("");
        txtCelular.setText("");
        txtObservaciones.setText("");
        recuperaCliente();
        lblMensaje.setText("Cantidad de Mascotas guardadas: " + ctrl.nroClientes() + " angelitos.");

    }

    /***
     * recuperacliente() --> Es una manera de escribir el nro de cliente
     * El numero de Cliente se asigna solo con la persistencia
     * Le da un formato de tres digitos 
     */
    private String recuperaCliente() {

        int nroCliente = ctrl.ultimoNroCliente();

        String nroT = "00" + nroCliente;
        nroT = nroT.substring(nroT.length() - 3);

        return nroT;

    }
    ;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbAlergico;
    private javax.swing.JComboBox<String> cmbAtencionEspecial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpBotones;
    private javax.swing.JPanel jpDatos;
    private javax.swing.JPanel jpImagen;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCelular1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblColor1;
    private javax.swing.JLabel lblColor2;
    private javax.swing.JLabel lblDueno;
    private javax.swing.JLabel lblImagenPelu;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRaza;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtDueno;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextField txtRaza;
    // End of variables declaration//GEN-END:variables
}
